include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    missing_required_param: error
    missing_return: error

  exclude:
    - test/.test_coverage.dart
    - lib/generated_plugin_registrant.dart
    - lib/gen/assets.gen.dart

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
