# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'newsfeed_app' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for newsfeed_app
  flutter_application_path = '../flutter_nps'
  load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')
  install_all_flutter_pods(flutter_application_path)

  target 'newsfeed_appTests' do
    inherit! :search_paths
    # Pods for testing
    install_all_flutter_pods(flutter_application_path)
  end

  target 'newsfeed_appUITests' do
    # Pods for testing
    install_all_flutter_pods(flutter_application_path)
  end

end
